### ISSUE TITLE
syntax

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta.gam#2]
@dill what do you think the syntax for using this package should look like?

Currently `smooths()` returns a list of the design matrix for training, for prediction, and the parameter vector. It then requires the user to evaluate the smooth function via matrix multiplication.

We could instead make it look like the [gretaGP](https://github.com/greta-dev/gretaGP#readme) package, where the thing returned is a vector that's ready to use, and that can be predicted/project from:

gretaGP:
```r
f = gp(x, kernel)
distribution(y) = normal(f, obs_sd)
f_plot <- project(f, x_plot)
```

equivalent gretaGAM option:
```r
f = smooths(~s(x), data = data.frame(x = x))
distribution(y) = normal(f, obs_sd)
f_plot <- project(f, data = data.frame(x = x_plot))
```

gretaGP makes all the GP components available (but hidden) as [an attribute](https://github.com/greta-dev/gretaGP/blob/master/R/gp.R#L85-L89) of the greta array it returns, and `project()` uses that to evaluate the GP at new data. So we could do the same here, like this:
```r
attr(f, "gam_info") <- jags_stuff
```

What do you think, should it look the same as gretaGP, or is there some other syntax that's nicer?

**Comment by dill** [comment]
I like this proposal!

The only thing I'm not keen on is using the word "project", imo this should be "predict". (To me) project implies extrapolation outside of the data and in particular in a time series type situation. In reality we are likely interested in making *predictions* both within and outwith the data.

Is "project" a gp-centric term? Can we do both?

**Comment by goldingn** [comment]
yeah I think `predict()` makes sense given this is an mgcv wrapper.

'project' isn't really a GP thing, but you evaluate the function at new locations by multiplication with a projection matrix. 'predict' didn't make sense for that since you often do it within a model.

**Comment by goldingn** [comment]
BTW I'm planning to rename this package `greta.gam`, and all other packages `greta.<something>` for consistency. Sound OK?

**Comment by dill** [comment]
All sounds good to me!
