### ISSUE TITLE
Change package name to `greta.gam`

### ISSUE THREAD

**Issue by njtierney** [greta-dev/greta.gam#4]
For the R Universe builds to work for this the package needs to have the same name as the repo:

> ERROR updating greta.gam from https://github.com/greta-dev/greta.gam (Package 'greta.gam' from registry does not match package name in description file: 'gretaGAM')

So the package should be `greta.gam`, I think? This follows the trend of `greta.dynamics`, etc.

**Comment by goldingn** [comment]
fixed in #3
