### ISSUE TITLE
passing smoothing parameter priors to `jagam2greta`

### ISSUE THREAD

**Issue by dill** [greta-dev/greta.gam#5]
At the moment we check if `sp` is `NULL` then assign a gamma prior to it. BUT we would probably like to supply a `greta` array from other priors. This would break `jagam`, so do something clever.

**Comment by goldingn** [comment]
I don't think it would break it necessarily - if it's not-null it just gets passed straight through. But it will break it if it is incorrectly specified (and it is hard for the user to know the specification). So we should probably just check the dimensions and error informatively if incorrect to let the user know how they need to change their input.

**Comment by dill** [comment]
I'm thinking that if `jagam` expects that `sp` is a numeric vector and we give it a `greta` array then it might be really unhappy about that?

**Comment by goldingn** [comment]
It's expecting a greta array at the moment (we create one internally with `greta::gamma()`), so I think only the dimensions are the issue

**Comment by dill** [comment]
I tried to make an example of it not working  but I couldn't so I assume you are right and this works :)
